/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_avance2;
import javax.swing.JOptionPane;


/**
 *
 * @author PC
 */
public class Boleta extends javax.swing.JFrame {

    /**
     * Creates new form Boleta
     */
    public Boleta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBoleta = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ventas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBoleta.setEditable(false);
        txtBoleta.setBackground(new java.awt.Color(231, 231, 231));
        txtBoleta.setColumns(20);
        txtBoleta.setRows(5);
        getContentPane().add(txtBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 400, 150));

        Ventas.setBackground(new java.awt.Color(231, 231, 231));
        Ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Ventas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 400, 180));

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 710, 170, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Boleta.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentasMouseClicked
        PanelVentas p = new PanelVentas();
        txtBoleta.setText(p.txtBoletaProductoVenta.getText());
    }//GEN-LAST:event_VentasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        PanelVentas p = new PanelVentas();
        JOptionPane.showMessageDialog(this, "Venta Realizada");
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Ventas;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea txtBoleta;
    // End of variables declaration//GEN-END:variables
}
