/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_avance2;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class Credenciales extends javax.swing.JFrame {
    
    public int codigo;
    public String usuario;
    public String contra;
    public String nivel;
    public Date fecha_creacion;
    Usuarios Usuarios[];
    almacen_usuarios bdUsuarios = new almacen_usuarios();

    /**
     * Creates new form credenciales
     */
    public Credenciales() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.tblTablaUser.setModel(new table_users(bdUsuarios.getListarUsers()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nivelUser = new javax.swing.JTextField();
        txt_contraUser = new javax.swing.JPasswordField();
        txt_codigoUser = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTablaUser = new javax.swing.JTable();
        btn_agregarUser = new javax.swing.JButton();
        btn_eliminarUser = new javax.swing.JButton();
        txt_usuarioUser = new javax.swing.JTextField();
        btn_actualizarUser = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_nivelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 362, 250, 40));

        txt_contraUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contraUserActionPerformed(evt);
            }
        });
        getContentPane().add(txt_contraUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 282, 240, 40));

        txt_codigoUser.setEditable(false);
        txt_codigoUser.setEnabled(false);
        txt_codigoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoUserActionPerformed(evt);
            }
        });
        getContentPane().add(txt_codigoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 122, 240, 40));

        tblTablaUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblTablaUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTablaUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTablaUser);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 500, 220));

        btn_agregarUser.setText("Agregar");
        btn_agregarUser.setToolTipText("");
        btn_agregarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarUserActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 140, 50));

        btn_eliminarUser.setText("Eliminar");
        btn_eliminarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarUserActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 150, 50));

        txt_usuarioUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioUserActionPerformed(evt);
            }
        });
        getContentPane().add(txt_usuarioUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 202, 240, 40));

        btn_actualizarUser.setText("Actualizar");
        btn_actualizarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarUserActionPerformed(evt);
            }
        });
        getContentPane().add(btn_actualizarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 150, 50));

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 445, 150, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/credenciales.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_contraUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contraUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contraUserActionPerformed

    private void txt_codigoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoUserActionPerformed

    private void tblTablaUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTablaUserMouseClicked
        // TODO add your handling code here:
        Usuarios usuario = ((table_users) this.tblTablaUser.getModel()).detalle(this.tblTablaUser.getSelectedRow());
        this.txt_codigoUser.setText(String.valueOf(usuario.getCodigo()));
        this.txt_usuarioUser.setText(usuario.getUsuario());
        this.txt_contraUser.setText(String.valueOf(usuario.getContra()));
        this.txt_nivelUser.setText(String.valueOf(usuario.getNivel()));
    }//GEN-LAST:event_tblTablaUserMouseClicked
    public boolean validarDatos() {
        
        try {
            codigo = Integer.parseInt("".equals(txt_codigoUser.getText()) ? "0" : txt_codigoUser.getText());
            usuario = txt_usuarioUser.getText();
            contra = txt_contraUser.getText();
            nivel = txt_nivelUser.getText();
            fecha_creacion = new Date();
            return true;

        } catch (Exception e) {
            return false;
        }
    }
    public void limpiarDatos() {
        this.txt_codigoUser.setText("");
        this.txt_usuarioUser.setText("");
        this.txt_contraUser.setText("");
        this.txt_nivelUser.setText("");
    }
    private void btn_agregarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarUserActionPerformed
        // TODO add your handling code here:
        if (validarDatos()) {
            if (!bdUsuarios.validar(usuario)) {
                if (codigo == 0) {
                    int codigoAux = bdUsuarios.ultimoCodigo() + 1;
                    bdUsuarios.add_user(new Usuarios(codigoAux, usuario, contra, nivel,fecha_creacion));
                    this.tblTablaUser.setModel(new table_users(bdUsuarios.getListarUsers()));
                    limpiarDatos();
                    JOptionPane.showMessageDialog(this, "Usuario agegado correctamente", "Confirmacion", 1);
                } else {
                    JOptionPane.showMessageDialog(this, "Imposible agregar!, esta accion es permitida para actualizar o borrar", "Advertencia", 2);
                }
            } else {
                JOptionPane.showMessageDialog(this, "El usuario ya existe", "Advertencia", 2);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hay campos vacíos", "Advertencia", 2);
        }
    }//GEN-LAST:event_btn_agregarUserActionPerformed

    private void btn_eliminarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarUserActionPerformed
        // TODO add your handling code here:
        if (validarDatos()) {
            bdUsuarios.delete_user(new Usuarios(codigo, usuario, contra, nivel,fecha_creacion));
            this.tblTablaUser.setModel(new table_users(bdUsuarios.getListarUsers()));
            limpiarDatos();
            JOptionPane.showMessageDialog(this, "Usuario eliminado exitosamente", "Confirmacion", 1);
        } else {
            JOptionPane.showMessageDialog(this, "Hay campos vacíos", "Advertencia", 2);
        }
    }//GEN-LAST:event_btn_eliminarUserActionPerformed

    private void btn_actualizarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarUserActionPerformed
        // TODO add your handling code here:
        if (validarDatos()) {
            bdUsuarios.actualizar(new Usuarios(codigo, usuario, contra, nivel,fecha_creacion));
            this.tblTablaUser.setModel(new table_users(bdUsuarios.getListarUsers()));
            limpiarDatos();
            JOptionPane.showMessageDialog(this, "Usuario actualizado exitosamente", "Confirmacion", 1);
        } else {
            JOptionPane.showMessageDialog(this, "Hya campos vacíos", "Advertencia", 2);
        }
    }//GEN-LAST:event_btn_actualizarUserActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        menu_principal menup= new menu_principal();
        menup.setVisible(true);
        this.dispose();
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void txt_usuarioUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioUserActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizarUser;
    private javax.swing.JButton btn_agregarUser;
    private javax.swing.JButton btn_eliminarUser;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTablaUser;
    private javax.swing.JTextField txt_codigoUser;
    private javax.swing.JPasswordField txt_contraUser;
    private javax.swing.JTextField txt_nivelUser;
    private javax.swing.JTextField txt_usuarioUser;
    // End of variables declaration//GEN-END:variables
}
