/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_avance2;

import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_nombreLogin = new javax.swing.JTextField();
        entrarLogin = new javax.swing.JButton();
        txt_contraseLogin = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nombreLogin.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txt_nombreLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_nombreLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreLoginActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nombreLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 200, 40));

        entrarLogin.setBackground(new java.awt.Color(255, 255, 255));
        entrarLogin.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        entrarLogin.setBorder(null);
        entrarLogin.setBorderPainted(false);
        entrarLogin.setContentAreaFilled(false);
        entrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarLoginActionPerformed(evt);
            }
        });
        jPanel1.add(entrarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 210, 60));
        jPanel1.add(txt_contraseLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/login.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreLoginActionPerformed

    private void entrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarLoginActionPerformed
        String usuario=txt_nombreLogin.getText();
        String cd=txt_contraseLogin.getText();
        menu_principal objeto_ventana=new menu_principal();
        menu_principal_empleado pv= new menu_principal_empleado();
        
        if(cd.equals("tienda1234")&& usuario.equals("admin")){
            objeto_ventana.setVisible(true);
            this.dispose();
        }
        else if(cd.equals("empleado")&& usuario.equals("cajero01")){
            pv.setVisible(true);
            this.dispose();
        }
        else if(cd.equals("") || usuario.equals("")){
           JOptionPane.showMessageDialog(this,"las cajas estan vacias");
           LimpiarEntradas();
        }
        else{
            JOptionPane.showMessageDialog(this,"contraseña o nombre incorrecto");
            LimpiarEntradas();
        }
        
    }//GEN-LAST:event_entrarLoginActionPerformed

    private void LimpiarEntradas(){
        txt_nombreLogin.setText("");
        txt_contraseLogin.setText("");
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrarLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_contraseLogin;
    private javax.swing.JTextField txt_nombreLogin;
    // End of variables declaration//GEN-END:variables
}
