/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_avance2;

/**
 *
 * @author Frank.P.Oscco
 */
public class Menu_Proveedores extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Proveedores
     */
    public Menu_Proveedores() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistroProveedor = new javax.swing.JButton();
        GenerarPedido = new javax.swing.JButton();
        jButtonMenuProoveRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistroProveedor.setBorder(null);
        RegistroProveedor.setBorderPainted(false);
        RegistroProveedor.setContentAreaFilled(false);
        RegistroProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(RegistroProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 190, 70));

        GenerarPedido.setBorder(null);
        GenerarPedido.setBorderPainted(false);
        GenerarPedido.setContentAreaFilled(false);
        GenerarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(GenerarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 190, 70));

        jButtonMenuProoveRegresar.setBorder(null);
        jButtonMenuProoveRegresar.setBorderPainted(false);
        jButtonMenuProoveRegresar.setContentAreaFilled(false);
        jButtonMenuProoveRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuProoveRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMenuProoveRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/MenuProvedorees.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroProveedorActionPerformed
        RegistrarProv RP=new RegistrarProv();
        RP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegistroProveedorActionPerformed

    private void GenerarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarPedidoActionPerformed
        PedidoProv PC = new PedidoProv();
        PC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GenerarPedidoActionPerformed

    private void jButtonMenuProoveRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuProoveRegresarActionPerformed
        menu_principal mps= new menu_principal();
        mps.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonMenuProoveRegresarActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerarPedido;
    private javax.swing.JButton RegistroProveedor;
    private javax.swing.JButton jButtonMenuProoveRegresar;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
