/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_avance2;

/**
 *
 * @author Marco
 */
public class menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form menu_principal
     */
    public menu_principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonMenuProd = new javax.swing.JButton();
        jButtonMenuProveedores = new javax.swing.JButton();
        jButtonMenuVentas = new javax.swing.JButton();
        jButtonMenuUsuarios = new javax.swing.JButton();
        jButtonMenuLogout = new javax.swing.JButton();
        jButtonMenuRV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        setForeground(new java.awt.Color(0, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMenuProd.setBorder(null);
        jButtonMenuProd.setBorderPainted(false);
        jButtonMenuProd.setContentAreaFilled(false);
        jButtonMenuProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuProdActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMenuProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 260, 50));

        jButtonMenuProveedores.setBorder(null);
        jButtonMenuProveedores.setBorderPainted(false);
        jButtonMenuProveedores.setContentAreaFilled(false);
        jButtonMenuProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuProveedoresActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMenuProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 230, 50));

        jButtonMenuVentas.setBorder(null);
        jButtonMenuVentas.setBorderPainted(false);
        jButtonMenuVentas.setContentAreaFilled(false);
        jButtonMenuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuVentasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMenuVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 260, 50));

        jButtonMenuUsuarios.setBorder(null);
        jButtonMenuUsuarios.setBorderPainted(false);
        jButtonMenuUsuarios.setContentAreaFilled(false);
        jButtonMenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMenuUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 220, 50));

        jButtonMenuLogout.setBorder(null);
        jButtonMenuLogout.setBorderPainted(false);
        jButtonMenuLogout.setContentAreaFilled(false);
        jButtonMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMenuLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 220, 50));

        jButtonMenuRV.setBorder(null);
        jButtonMenuRV.setBorderPainted(false);
        jButtonMenuRV.setContentAreaFilled(false);
        jButtonMenuRV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuRVActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMenuRV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 260, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/admin.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuProdActionPerformed
    Productos_JFrame prodjf= new Productos_JFrame();
    prodjf.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonMenuProdActionPerformed

    private void jButtonMenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuUsuariosActionPerformed
    Credenciales cred= new Credenciales();
    cred.setVisible(true);
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenuUsuariosActionPerformed

    private void jButtonMenuProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuProveedoresActionPerformed
    Menu_Proveedores prov= new Menu_Proveedores();
    prov.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonMenuProveedoresActionPerformed

    private void jButtonMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuLogoutActionPerformed
    login log=new login();
    log.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonMenuLogoutActionPerformed

    private void jButtonMenuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuVentasActionPerformed
    PanelVentas pv=new PanelVentas();
    pv.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonMenuVentasActionPerformed

    private void jButtonMenuRVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuRVActionPerformed
    Resumen_Ventas_frame rven= new Resumen_Ventas_frame();
    rven.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonMenuRVActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMenuLogout;
    private javax.swing.JButton jButtonMenuProd;
    private javax.swing.JButton jButtonMenuProveedores;
    private javax.swing.JButton jButtonMenuRV;
    private javax.swing.JButton jButtonMenuUsuarios;
    private javax.swing.JButton jButtonMenuVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
