/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_avance2;

/**
 *
 * @author Marco
 */
public class menu_principal_empleado extends javax.swing.JFrame {

    /**
     * Creates new form menu_principal
     */
    public menu_principal_empleado() {
        initComponents();
        this.setLocationRelativeTo(null);
        jButtonEmpMPProd.setEnabled(false);
        jButtonEmpMPProveedores.setEnabled(false);
        jButtonEmpMPUsuarios.setEnabled(false);
        jButtonEmpMPRV.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonEmpMPVentas = new javax.swing.JButton();
        jButtonCloseEmpMP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonEmpMPRV = new javax.swing.JButton();
        jButtonEmpMPProd = new javax.swing.JButton();
        jButtonEmpMPProveedores = new javax.swing.JButton();
        jButtonEmpMPUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        setForeground(new java.awt.Color(0, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEmpMPVentas.setBorder(null);
        jButtonEmpMPVentas.setBorderPainted(false);
        jButtonEmpMPVentas.setContentAreaFilled(false);
        jButtonEmpMPVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpMPVentasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEmpMPVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 220, 90));

        jButtonCloseEmpMP.setBorder(null);
        jButtonCloseEmpMP.setBorderPainted(false);
        jButtonCloseEmpMP.setContentAreaFilled(false);
        jButtonCloseEmpMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseEmpMPActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCloseEmpMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 220, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cajero.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        jButtonEmpMPRV.setText("Resumen de Ventas");
        jButtonEmpMPRV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpMPRVActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEmpMPRV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, 60));

        jButtonEmpMPProd.setText("Productos");
        jButtonEmpMPProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpMPProdActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEmpMPProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, 50));

        jButtonEmpMPProveedores.setText("Proveedores");
        jButtonEmpMPProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpMPProveedoresActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEmpMPProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 150, 50));

        jButtonEmpMPUsuarios.setText("Editar Credenciales");
        jButtonEmpMPUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpMPUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEmpMPUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 150, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEmpMPProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpMPProdActionPerformed
    Productos_JFrame prodjf= new Productos_JFrame();
    prodjf.setVisible(true);
    this.dispose();
    
    }//GEN-LAST:event_jButtonEmpMPProdActionPerformed

    private void jButtonEmpMPUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpMPUsuariosActionPerformed
    Credenciales cred= new Credenciales();
    cred.setVisible(true);
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButtonEmpMPUsuariosActionPerformed

    private void jButtonEmpMPProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpMPProveedoresActionPerformed
    Menu_Proveedores prov= new Menu_Proveedores();
    prov.setVisible(true);
    this.dispose();
    
    }//GEN-LAST:event_jButtonEmpMPProveedoresActionPerformed

    private void jButtonCloseEmpMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseEmpMPActionPerformed
    login log=new login();
    log.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonCloseEmpMPActionPerformed

    private void jButtonEmpMPVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpMPVentasActionPerformed
    PanelVentas pv=new PanelVentas();
    pv.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonEmpMPVentasActionPerformed

    private void jButtonEmpMPRVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpMPRVActionPerformed
        Resumen_Ventas_frame rven= new Resumen_Ventas_frame();
        rven.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonEmpMPRVActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCloseEmpMP;
    private javax.swing.JButton jButtonEmpMPProd;
    private javax.swing.JButton jButtonEmpMPProveedores;
    private javax.swing.JButton jButtonEmpMPRV;
    private javax.swing.JButton jButtonEmpMPUsuarios;
    private javax.swing.JButton jButtonEmpMPVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
