/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_avance2;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Frank.P.Oscco
 */
public class PedidoProv extends javax.swing.JFrame {

    ArrayList<Datos_Proveedores> listaProv=new ArrayList<Datos_Proveedores>();
    
    public PedidoProv() {
        initComponents();
        this.setLocationRelativeTo(null);
        addRowToJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Nomprov = new javax.swing.JTextField();
        txt_NomEmpre = new javax.swing.JTextField();
        txt_Ruc = new javax.swing.JTextField();
        txt_Producto = new javax.swing.JTextField();
        txt_Celular = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_proveedores = new javax.swing.JTable();
        Btn_Regresar = new javax.swing.JButton();
        Btn_RegistrarPedido = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ListaPedido = new javax.swing.JTextArea();
        txt_ProducOrden = new javax.swing.JTextField();
        txt_Dni = new javax.swing.JTextField();
        txt_NameLastName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_Direccion = new javax.swing.JTextField();
        txt_CantOrden = new javax.swing.JTextField();
        txt_Marca = new javax.swing.JTextField();
        Btn_Limpiar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Nomprov.setEditable(false);
        txt_Nomprov.setBackground(new java.awt.Color(255, 255, 255));
        txt_Nomprov.setBorder(null);
        getContentPane().add(txt_Nomprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 240, 40));

        txt_NomEmpre.setEditable(false);
        txt_NomEmpre.setBackground(new java.awt.Color(255, 255, 255));
        txt_NomEmpre.setBorder(null);
        getContentPane().add(txt_NomEmpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 240, 40));

        txt_Ruc.setEditable(false);
        txt_Ruc.setBackground(new java.awt.Color(255, 255, 255));
        txt_Ruc.setBorder(null);
        getContentPane().add(txt_Ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 240, 40));

        txt_Producto.setEditable(false);
        txt_Producto.setBackground(new java.awt.Color(255, 255, 255));
        txt_Producto.setBorder(null);
        getContentPane().add(txt_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 230, 30));

        txt_Celular.setEditable(false);
        txt_Celular.setBackground(new java.awt.Color(255, 255, 255));
        txt_Celular.setBorder(null);
        getContentPane().add(txt_Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 230, 30));

        Tb_proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom_Proveedor", "Nom_Empresa", "Ruc", "Producto", "Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tb_proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_proveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tb_proveedores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 550, 240));

        Btn_Regresar.setBorder(null);
        Btn_Regresar.setBorderPainted(false);
        Btn_Regresar.setContentAreaFilled(false);
        Btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 148, 50));

        Btn_RegistrarPedido.setBorder(null);
        Btn_RegistrarPedido.setBorderPainted(false);
        Btn_RegistrarPedido.setContentAreaFilled(false);
        Btn_RegistrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RegistrarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_RegistrarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 560, 200, 50));

        txt_ListaPedido.setEditable(false);
        txt_ListaPedido.setColumns(20);
        txt_ListaPedido.setRows(5);
        jScrollPane2.setViewportView(txt_ListaPedido);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 430, 240));

        txt_ProducOrden.setBorder(null);
        getContentPane().add(txt_ProducOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 230, 40));

        txt_Dni.setBorder(null);
        getContentPane().add(txt_Dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 240, 30));

        txt_NameLastName.setBorder(null);
        getContentPane().add(txt_NameLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 230, 30));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1028, 117, -1, -1));

        txt_Direccion.setBorder(null);
        getContentPane().add(txt_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 240, 40));

        txt_CantOrden.setBorder(null);
        getContentPane().add(txt_CantOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 230, 40));

        txt_Marca.setBorder(null);
        getContentPane().add(txt_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 230, 40));

        Btn_Limpiar.setBorder(null);
        Btn_Limpiar.setBorderPainted(false);
        Btn_Limpiar.setContentAreaFilled(false);
        Btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 560, 160, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/PedidoProv.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList DatosProv(){            
        Datos_Proveedores P1=new Datos_Proveedores("Francisco", "ProSierra SAC", "10345634341", "Verduras", "985475634");
        Datos_Proveedores P2=new Datos_Proveedores("Camilo", "Snack Peru SAC", "10456857672", "Snack y bebidas", "900645364");
        Datos_Proveedores P3=new Datos_Proveedores("Freddy", "AgroAmbiente SAC", "10107465345", "Frutas", "990023452");
        Datos_Proveedores P4=new Datos_Proveedores("Andres", "Lon Menestras SAC", "10347658454", "Menestras", "911234645");
        Datos_Proveedores P5=new Datos_Proveedores("Jose Maria", "CultivosSierra SAC", "10984734851", "Abarrotes", "918746535");
        Datos_Proveedores P6=new Datos_Proveedores("Remigio", "VegetalPeru SAC", "10334653883", "Verduras", "912836356");
        Datos_Proveedores P7=new Datos_Proveedores("Arturo", "EnlatadosF SAC", "10876457334", "Conservas", "954634443");
        Datos_Proveedores P8=new Datos_Proveedores("Jhosep", "Colorina SAC", "10102343754", "Golosinas", "932323434");
        Datos_Proveedores P9=new Datos_Proveedores("Angel", "FloraPeru SAC", "10323544564", "Verduras", "900303234");
        Datos_Proveedores P10=new Datos_Proveedores("Fabricio", "Los paisanos SAC", "10745635485", "Tuberculos", "943010901");
        listaProv.add(P1);
        listaProv.add(P2);
        listaProv.add(P3);
        listaProv.add(P4);
        listaProv.add(P5);
        listaProv.add(P6);
        listaProv.add(P7);
        listaProv.add(P8);
        listaProv.add(P9);
        listaProv.add(P10);
                
        return listaProv;
    }
    
    public void addRowToJTable(){
        DefaultTableModel tablaProv = (DefaultTableModel) Tb_proveedores.getModel();
        
        ArrayList<Datos_Proveedores> listaProv=DatosProv();
        
        Object rowData[] = new Object[5];
        
        for(int i=0; i<listaProv.size(); i++){
            
            rowData[0] = listaProv.get(i).NombreProv;
            rowData[1] = listaProv.get(i).NomEmpresa;
            rowData[2] = listaProv.get(i).Ruc;
            rowData[3] = listaProv.get(i).Producto;
            rowData[4] = listaProv.get(i).Celular;           
            
            tablaProv.addRow(rowData);
        }
    }
    
    private void Btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RegresarActionPerformed
        Menu_Proveedores back = new Menu_Proveedores();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_RegresarActionPerformed

    private void Tb_proveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_proveedoresMouseClicked
        DefaultTableModel tablaProv=(DefaultTableModel)Tb_proveedores.getModel();

    String NombreProv=tablaProv.getValueAt(Tb_proveedores.getSelectedRow(), 0).toString();
    String NombreEmpre=tablaProv.getValueAt(Tb_proveedores.getSelectedRow(), 1).toString();
    String Ruc=tablaProv.getValueAt(Tb_proveedores.getSelectedRow(), 2).toString();
    String Produc=tablaProv.getValueAt(Tb_proveedores.getSelectedRow(), 3).toString();
    String Celular=tablaProv.getValueAt(Tb_proveedores.getSelectedRow(), 4).toString();
    
    txt_Nomprov.setText(NombreProv);
    txt_NomEmpre.setText(NombreEmpre);
    txt_Ruc.setText(Ruc);
    txt_Producto.setText(Produc);
    txt_Celular.setText(Celular);
    }//GEN-LAST:event_Tb_proveedoresMouseClicked

    private void Btn_RegistrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RegistrarPedidoActionPerformed
        if(txt_NameLastName.getText().equals("")||txt_Dni.getText().equals("")||txt_Direccion.getText().equals("")||txt_ProducOrden.getText().equals("")||txt_Marca.getText().equals("")||txt_CantOrden.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Formulario vacio, completelo por favor");
        }else{       
        String NomProveedor=txt_Nomprov.getText();
        String NomEmpresa=txt_NomEmpre.getText();
        String Ruc=txt_Ruc.getText();
        String Producto= txt_Producto.getText();
        String Celular=txt_Celular.getText();
        
        String NombreApellido=txt_NameLastName.getText();
        String Dni=txt_Dni.getText();
        String Dirección=txt_Direccion.getText();
        
        String ProductoFaltante=txt_ProducOrden.getText();
        String Marca=txt_Marca.getText();
        String Cantidad=txt_CantOrden.getText();
                
        String Pedido="========  Orden de Pedido  ========="
            +"\n"
            +"\n"
            +"\nDatos del proveedor"
            +"\n-----------------------------------------------------------"  
            +"\n. Nombre del proveedor:   "+NomProveedor
            +"\n. Nombre de la empresa:   "+NomEmpresa
            +"\n. Numero RUC:   "+Ruc
            +"\n. Producto:   "+Producto
            +"\n. Celular de proveedor:   "+Celular
            +"\n-----------------------------------------------------------"
            +"\n"
            +"\n"
            +"\nDatos Personales"
            +"\n-----------------------------------------------------------"
            +"\n. Nombres y apellido:   "+NombreApellido
            +"\n. Dni:    "+Dni
            +"\n. Dirección:    "+Dirección
            +"\n"
            +"\n"
            +"\nProducto requerido"
            +"\n-----------------------------------------------------------"
            +"\n. Producto requerido:    "+ProductoFaltante
            +"\n. Marca del producto :    "+Marca    
            +"\n. Cantidad :    "+Cantidad    
            ;
        
        txt_ListaPedido.setText(Pedido);
        }   
    }//GEN-LAST:event_Btn_RegistrarPedidoActionPerformed

    private void Btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarActionPerformed
        txt_NameLastName.setText("");
        txt_Dni.setText("");
        txt_Direccion.setText("");
        txt_ProducOrden.setText("");
        txt_Marca.setText("");
        txt_CantOrden.setText("");
    }//GEN-LAST:event_Btn_LimpiarActionPerformed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Limpiar;
    private javax.swing.JButton Btn_RegistrarPedido;
    private javax.swing.JButton Btn_Regresar;
    private javax.swing.JTable Tb_proveedores;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_CantOrden;
    private javax.swing.JTextField txt_Celular;
    private javax.swing.JTextField txt_Direccion;
    private javax.swing.JTextField txt_Dni;
    private javax.swing.JTextArea txt_ListaPedido;
    private javax.swing.JTextField txt_Marca;
    private javax.swing.JTextField txt_NameLastName;
    private javax.swing.JTextField txt_NomEmpre;
    private javax.swing.JTextField txt_Nomprov;
    private javax.swing.JTextField txt_ProducOrden;
    private javax.swing.JTextField txt_Producto;
    private javax.swing.JTextField txt_Ruc;
    // End of variables declaration//GEN-END:variables
}
