/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_avance2;

import javax.swing.JOptionPane;

/**
 *
 * @author Bruno Sandoval
 */
public class Productos_JFrame extends javax.swing.JFrame {

    public int codigo;
    public String nombre;
    public double precio;
    public int inventario;
    public String fVencimiento;
    public String fLlegada;
    public String unidad;
    public String descripcion;
    Producto Productos[];
    AlmacenamientoProductos bdProductos = new AlmacenamientoProductos();

    /**
     * Creates new form Productos_JFrame
     */
    public Productos_JFrame() {
        initComponents();
        bdProductos.cargarProductos();
        this.tblTabla.setModel(new TableModelProducto(bdProductos.getListaProductos()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtCodigoProducto1 = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        txtPrecioProducto = new javax.swing.JTextField();
        txtInventarioProducto = new javax.swing.JTextField();
        btnAgregarProductos = new javax.swing.JButton();
        btnActualizarProductos = new javax.swing.JButton();
        btnEliminarProductos = new javax.swing.JButton();
        jButtonGbackrProductos = new javax.swing.JButton();
        txtFVencimiento = new javax.swing.JTextField();
        txtFLlegada = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtUnidad = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigoProducto1.setEditable(false);
        txtCodigoProducto1.setEnabled(false);
        txtCodigoProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProducto1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigoProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 250, 30));

        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 250, 30));
        getContentPane().add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 250, 30));

        txtInventarioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInventarioProductoActionPerformed(evt);
            }
        });
        getContentPane().add(txtInventarioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 250, 30));

        btnAgregarProductos.setToolTipText("");
        btnAgregarProductos.setBorder(null);
        btnAgregarProductos.setBorderPainted(false);
        btnAgregarProductos.setContentAreaFilled(false);
        btnAgregarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 130, 40));

        btnActualizarProductos.setBorder(null);
        btnActualizarProductos.setBorderPainted(false);
        btnActualizarProductos.setContentAreaFilled(false);
        btnActualizarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 280, 40));

        btnEliminarProductos.setBorder(null);
        btnEliminarProductos.setBorderPainted(false);
        btnEliminarProductos.setContentAreaFilled(false);
        btnEliminarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 130, 40));

        jButtonGbackrProductos.setBorder(null);
        jButtonGbackrProductos.setBorderPainted(false);
        jButtonGbackrProductos.setContentAreaFilled(false);
        jButtonGbackrProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGbackrProductosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGbackrProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 120, 30));

        txtFVencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFVencimientoActionPerformed(evt);
            }
        });
        getContentPane().add(txtFVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 250, 30));
        getContentPane().add(txtFLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 250, 30));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 250, 30));

        txtUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 250, 30));

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTablaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTabla);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 530, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Productos.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProducto1ActionPerformed

    private void btnAgregarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductosActionPerformed
        // TODO add your handling code here:
        if (validarDatos()) {
            if (!bdProductos.verificarExistencia(nombre)) {
                if (codigo == 0) {
                    int codigoAux = bdProductos.ultimoCodigo() + 1;
                    bdProductos.agregar(new Producto(codigoAux, nombre, precio, inventario,fVencimiento,fLlegada,descripcion, unidad));
                    this.tblTabla.setModel(new TableModelProducto(bdProductos.getListaProductos()));
                    limpiarDatos();
                    JOptionPane.showMessageDialog(this, "Producto agegado exitosamente", "Confirmacion", 1);
                } else {
                    JOptionPane.showMessageDialog(this, "Imposible agregar!, esta accion es permitida para actualizar o borrar", "Advertencia", 2);
                }
            } else {
                JOptionPane.showMessageDialog(this, "El producto ya existe", "Advertencia", 2);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Alguno de los valores digitados esta vacio o es erroneo", "Advertencia", 2);
        }
    }//GEN-LAST:event_btnAgregarProductosActionPerformed

    private void btnActualizarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProductosActionPerformed
        // TODO add your handling code here:
        if (validarDatos()) {
            bdProductos.actualizar(new Producto(codigo, nombre, precio, inventario,fVencimiento,fLlegada,descripcion, unidad));
            this.tblTabla.setModel(new TableModelProducto(bdProductos.getListaProductos()));
            limpiarDatos();
            JOptionPane.showMessageDialog(this, "Producto actualizado exitosamente", "Confirmacion", 1);
        } else {
            JOptionPane.showMessageDialog(this, "Alguno de los valores digitados esta vacio o es erroneo", "Advertencia", 2);
        }
    }//GEN-LAST:event_btnActualizarProductosActionPerformed

    private void btnEliminarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductosActionPerformed
        // TODO add your handling code here:
        if (validarDatos()) {
            bdProductos.borrar(new Producto(codigo, nombre, precio, inventario,fVencimiento,fLlegada,descripcion, unidad));
            this.tblTabla.setModel(new TableModelProducto(bdProductos.getListaProductos()));
            limpiarDatos();
            JOptionPane.showMessageDialog(this, "Producto eliminado exitosamente", "Confirmacion", 1);
        } else {
            JOptionPane.showMessageDialog(this, "Alguno de los valores digitados esta vacio o es erroneo", "Advertencia", 2);
        }
    }//GEN-LAST:event_btnEliminarProductosActionPerformed

    private void jButtonGbackrProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGbackrProductosActionPerformed
    menu_principal mpr= new menu_principal();
    mpr.setVisible(true);
    this.dispose();
    
    }//GEN-LAST:event_jButtonGbackrProductosActionPerformed

    private void txtInventarioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInventarioProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInventarioProductoActionPerformed

    private void txtFVencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFVencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFVencimientoActionPerformed

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void tblTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTablaMouseClicked
        // TODO add your handling code here:
        Producto producto = ((TableModelProducto) this.tblTabla.getModel()).detalle(this.tblTabla.getSelectedRow());
        this.txtCodigoProducto1.setText(String.valueOf(producto.getCodigo()));
        this.txtNombreProducto.setText(producto.getNombre());
        this.txtPrecioProducto.setText(String.valueOf(producto.getPrecio()));
        this.txtInventarioProducto.setText(String.valueOf(producto.getInventario()));
        this.txtFLlegada.setText(String.valueOf(producto.getfLlegada()));
        this.txtFVencimiento.setText(String.valueOf(producto.getfVencimiento()));
        this.txtUnidad.setText(String.valueOf(producto.getUnidad()));
        this.txtDescripcion.setText(String.valueOf(producto.getDescripcion()));
    }//GEN-LAST:event_tblTablaMouseClicked

    private void txtUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadActionPerformed

    public boolean validarDatos() {
        try {
            codigo = Integer.parseInt("".equals(txtCodigoProducto1.getText()) ? "0" : txtCodigoProducto1.getText());
            nombre = txtNombreProducto.getText();
            precio = Double.parseDouble(txtPrecioProducto.getText());
            inventario = Integer.parseInt(txtInventarioProducto.getText());
            fVencimiento = txtFVencimiento.getText();
            fLlegada = txtFLlegada.getText();
            unidad = txtUnidad.getText();
            descripcion = txtDescripcion.getText();
            return true;

        } catch (Exception e) {
            return false;
        }
    }

    public void limpiarDatos() {
        this.txtCodigoProducto1.setText("");
        this.txtNombreProducto.setText("");
        this.txtPrecioProducto.setText("");
        this.txtInventarioProducto.setText("");
        this.txtFLlegada.setText("");
        this.txtFVencimiento.setText("");
        this.txtDescripcion.setText("");
        this.txtUnidad.setText("");
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarProductos;
    private javax.swing.JButton btnAgregarProductos;
    private javax.swing.JButton btnEliminarProductos;
    private javax.swing.JButton jButtonGbackrProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblTabla;
    private javax.swing.JTextField txtCodigoProducto1;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFLlegada;
    private javax.swing.JTextField txtFVencimiento;
    private javax.swing.JTextField txtInventarioProducto;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioProducto;
    private javax.swing.JTextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
