/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_avance2;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Frank.P.Oscco
 */
public class RegistrarProv extends javax.swing.JFrame {

    ArrayList<Datos_Proveedores> listaProv=new ArrayList<Datos_Proveedores>();
    
    
    public RegistrarProv() {
        initComponents();
        this. setLocationRelativeTo(null);
        addRowToJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_NomProv = new javax.swing.JTextField();
        txt_NomEmpre = new javax.swing.JTextField();
        txt_Ruc = new javax.swing.JTextField();
        txt_Product = new javax.swing.JTextField();
        txt_Celular = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_proveedores = new javax.swing.JTable();
        Btn_LimpiarForm = new javax.swing.JButton();
        Btn_AgregarProv = new javax.swing.JButton();
        Btn_EliminarProv = new javax.swing.JButton();
        Btn_ModificarInfo = new javax.swing.JButton();
        Btn_regresar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_NomProv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_NomProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomProvActionPerformed(evt);
            }
        });
        getContentPane().add(txt_NomProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 250, 33));

        txt_NomEmpre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_NomEmpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 250, 40));

        txt_Ruc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_Ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 250, 40));

        txt_Product.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_Product, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 250, 29));

        txt_Celular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 250, 33));

        Tb_proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom_Proveedor", "Nom_Empresa", "Ruc", "Producto", "Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tb_proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_proveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tb_proveedores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 650, 300));

        Btn_LimpiarForm.setBorder(null);
        Btn_LimpiarForm.setBorderPainted(false);
        Btn_LimpiarForm.setContentAreaFilled(false);
        Btn_LimpiarForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarFormActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_LimpiarForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 160, 50));

        Btn_AgregarProv.setBorder(null);
        Btn_AgregarProv.setBorderPainted(false);
        Btn_AgregarProv.setContentAreaFilled(false);
        Btn_AgregarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgregarProvActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_AgregarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 160, 50));

        Btn_EliminarProv.setBorder(null);
        Btn_EliminarProv.setBorderPainted(false);
        Btn_EliminarProv.setContentAreaFilled(false);
        Btn_EliminarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarProvActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_EliminarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, 160, 50));

        Btn_ModificarInfo.setBorder(null);
        Btn_ModificarInfo.setBorderPainted(false);
        Btn_ModificarInfo.setContentAreaFilled(false);
        Btn_ModificarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModificarInfoActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_ModificarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 490, 160, 50));

        Btn_regresar.setBorder(null);
        Btn_regresar.setBorderPainted(false);
        Btn_regresar.setContentAreaFilled(false);
        Btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_regresarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 150, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/RegisProv.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList DatosProv(){            
        Datos_Proveedores P1=new Datos_Proveedores("Francisco", "ProSierra SAC", "10345634341", "Verduras", "985475634");
        Datos_Proveedores P2=new Datos_Proveedores("Camilo", "Snack Peru SAC", "10456857672", "Snack y bebidas", "900645364");
        Datos_Proveedores P3=new Datos_Proveedores("Freddy", "AgroAmbiente SAC", "10107465345", "Frutas", "990023452");
        Datos_Proveedores P4=new Datos_Proveedores("Andres", "Lon Menestras SAC", "10347658454", "Menestras", "911234645");
        Datos_Proveedores P5=new Datos_Proveedores("Jose Maria", "CultivosSierra SAC", "10984734851", "Abarrotes", "918746535");
        Datos_Proveedores P6=new Datos_Proveedores("Remigio", "Backus SAC", "10334653883", "Bebidas", "912836356");
        Datos_Proveedores P7=new Datos_Proveedores("Arturo", "EnlatadosF SAC", "10876457334", "Conservas", "954634443");
        Datos_Proveedores P8=new Datos_Proveedores("Jhosep", "Colorina SAC", "10102343754", "Golosinas", "932323434");
        Datos_Proveedores P9=new Datos_Proveedores("Angel", "FloraPeru SAC", "10323544564", "Verduras", "900303234");
        Datos_Proveedores P10=new Datos_Proveedores("Fabricio", "Los paisanos SAC", "10745635485", "Tuberculos", "943010901");
        
        listaProv.add(P1);
        listaProv.add(P2);
        listaProv.add(P3);
        listaProv.add(P4);
        listaProv.add(P5);
        listaProv.add(P6);
        listaProv.add(P7);
        listaProv.add(P8);
        listaProv.add(P9);
        listaProv.add(P10);
                
        return listaProv;
    }
    
    public void addRowToJTable(){
        DefaultTableModel tablaProv = (DefaultTableModel) Tb_proveedores.getModel();
        
        ArrayList<Datos_Proveedores> listaProv=DatosProv();
        
        Object rowData[] = new Object[5];
        
        for(int i=0; i<listaProv.size(); i++){
            
            rowData[0] = listaProv.get(i).NombreProv;
            rowData[1] = listaProv.get(i).NomEmpresa;
            rowData[2] = listaProv.get(i).Ruc;
            rowData[3] = listaProv.get(i).Producto;
            rowData[4] = listaProv.get(i).Celular;           
            
            tablaProv.addRow(rowData);
        }
    }
    
    
    
    private void Btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_regresarActionPerformed
        Menu_Proveedores back = new Menu_Proveedores();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_regresarActionPerformed

        
    private void Tb_proveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_proveedoresMouseClicked
    DefaultTableModel tablaProv=(DefaultTableModel)Tb_proveedores.getModel();

    String NombreProv=tablaProv.getValueAt(Tb_proveedores.getSelectedRow(), 0).toString();
    String NombreEmpre=tablaProv.getValueAt(Tb_proveedores.getSelectedRow(), 1).toString();
    String Ruc=tablaProv.getValueAt(Tb_proveedores.getSelectedRow(), 2).toString();
    String Produc=tablaProv.getValueAt(Tb_proveedores.getSelectedRow(), 3).toString();
    String Celular=tablaProv.getValueAt(Tb_proveedores.getSelectedRow(), 4).toString();
    
    txt_NomProv.setText(NombreProv);
    txt_NomEmpre.setText(NombreEmpre);
    txt_Ruc.setText(Ruc);
    txt_Product.setText(Produc);
    txt_Celular.setText(Celular);
    }//GEN-LAST:event_Tb_proveedoresMouseClicked

    private void Btn_LimpiarFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarFormActionPerformed
        txt_NomProv.setText("");
        txt_NomEmpre.setText("");
        txt_Ruc.setText("");
        txt_Product.setText("");
        txt_Celular.setText("");
    }//GEN-LAST:event_Btn_LimpiarFormActionPerformed

    private void Btn_AgregarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgregarProvActionPerformed
        if(txt_NomProv.getText().equals("") || txt_NomEmpre.getText().equals("") || txt_Ruc.getText().equals("") || txt_Product.getText().equals("") || txt_Celular.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, "Error, rellene las casillas");
            
        }else{
            
            String datos[]={txt_NomProv.getText(), txt_NomEmpre.getText(), txt_Ruc.getText() , txt_Product.getText() , txt_Celular.getText()};
            
            DefaultTableModel tabla=(DefaultTableModel)Tb_proveedores.getModel();
            tabla.addRow(datos);
            
            JOptionPane.showMessageDialog(this, "Datos registrados");
            
            txt_NomProv.setText("");
            txt_NomEmpre.setText("");
            txt_Ruc.setText("");
            txt_Product.setText("");
            txt_Celular.setText("");
        }
    }//GEN-LAST:event_Btn_AgregarProvActionPerformed

    private void Btn_EliminarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarProvActionPerformed
        DefaultTableModel tablaProv=(DefaultTableModel)Tb_proveedores.getModel();
        if(Tb_proveedores.getSelectedRowCount() == 1){
            JOptionPane.showMessageDialog(this, "Datos Eliminados");
            tablaProv.removeRow(Tb_proveedores.getSelectedRow());
        }else{
            if(Tb_proveedores.getSelectedRowCount() == 0){                
                JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar");
            }
        }
    }//GEN-LAST:event_Btn_EliminarProvActionPerformed

    private void Btn_ModificarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModificarInfoActionPerformed
        DefaultTableModel tablaProv=(DefaultTableModel)Tb_proveedores.getModel();
        
        if(Tb_proveedores.getSelectedRowCount() == 1){
            
            String NomProv = txt_NomProv.getText();
            String NomEmpre = txt_NomEmpre.getText();
            String Ruc = txt_Ruc.getText();
            String Producto=txt_Product.getText();
            String Celular=txt_Celular.getText();
            
            tablaProv.setValueAt(NomProv, Tb_proveedores.getSelectedRow(), 0);
            tablaProv.setValueAt(NomEmpre, Tb_proveedores.getSelectedRow(), 1);
            tablaProv.setValueAt(Ruc, Tb_proveedores.getSelectedRow(), 2);
            tablaProv.setValueAt(Producto, Tb_proveedores.getSelectedRow(), 3);
            tablaProv.setValueAt(Celular, Tb_proveedores.getSelectedRow(), 4);
            
            
            JOptionPane.showMessageDialog(this, "Modificación exitosa");
        
        }else{
            if(Tb_proveedores.getSelectedRowCount() == 0){
                JOptionPane.showMessageDialog(this, "Selecciona una fila para modificar");
            }
        }
    }//GEN-LAST:event_Btn_ModificarInfoActionPerformed

    private void txt_NomProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomProvActionPerformed

    
    
    
    
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_AgregarProv;
    private javax.swing.JButton Btn_EliminarProv;
    private javax.swing.JButton Btn_LimpiarForm;
    private javax.swing.JButton Btn_ModificarInfo;
    private javax.swing.JButton Btn_regresar;
    private javax.swing.JTable Tb_proveedores;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Celular;
    private javax.swing.JTextField txt_NomEmpre;
    private javax.swing.JTextField txt_NomProv;
    private javax.swing.JTextField txt_Product;
    private javax.swing.JTextField txt_Ruc;
    // End of variables declaration//GEN-END:variables
}
