/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_avance2;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marco
 */
public class Resumen_Ventas_frame extends javax.swing.JFrame {
    DefaultTableModel modeloVentas= new DefaultTableModel();
    public void CargarDatos(){
        ArrayList<Object>nomColum= new ArrayList<Object>();
        nomColum.add("Codigo de Venta");
        nomColum.add("Vendedor");
        nomColum.add("Comprador");
        nomColum.add("Descripción de Venta");
        nomColum.add("Precio Total");
        nomColum.add("Fecha de venta");

        for (Object columna : nomColum) {
            modeloVentas.addColumn(columna);
        }
        this.jTableVentasR.setModel(modeloVentas);
        ArrayList<Object[]>datosVen= new ArrayList<Object[]>();
        Object[]venta1= new Object[]{"V001","Cajero01","Juan L.","Manzanas,Peras, platano",50.0,"23/05/2023"};
        Object[]venta2= new Object[]{"V002","Cajero01","Carlos T.","Arroz, Huevo",45.0,"27/05/2023"};
        Object[]venta3= new Object[]{"V003","Cajero02","Bryan C.","Leche",10.0,"03/06/2023"};
        Object[]venta4= new Object[]{"V004","Cajero01","Luisa Z.","Fideo, Tomate",7.50,"06/06/2023"};
        Object[]venta5= new Object[]{"V005","Cajero03","Nicole M.","Arroz, Fideo, Platanos",27.0,"13/06/2023"};
        Object[]venta6= new Object[]{"V006","Cajero02","Andrea T.","Leche, Huevos, Manzanas",18.0,"20/06/2023"};
        
        datosVen.add(venta1);
        datosVen.add(venta2);
        datosVen.add(venta3);
        datosVen.add(venta4);
        datosVen.add(venta5);
        datosVen.add(venta6);
        
        for (Object[] DatosVentas : datosVen) {
            modeloVentas.addRow(DatosVentas);
        }
        jTableVentasR.setModel(modeloVentas);
        
    }
    /**
     * Creates new form Resumen_Ventas_frame
     */
    public Resumen_Ventas_frame() {
        initComponents();
        CargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVentasR = new javax.swing.JTable();
        jButtonRegresarRV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableVentasR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableVentasR);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 500, 310));

        jButtonRegresarRV.setBorder(null);
        jButtonRegresarRV.setBorderPainted(false);
        jButtonRegresarRV.setContentAreaFilled(false);
        jButtonRegresarRV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarRVActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresarRV, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 442, 150, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/resumen.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarRVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarRVActionPerformed
    menu_principal menup= new menu_principal();
    menup.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonRegresarRVActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegresarRV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVentasR;
    // End of variables declaration//GEN-END:variables
}
